### ISSUE TITLE
Can you change the  Xʀ to Xr\XR ？ Otherwise we have to encode....

### ISSUE THREAD

**Issue by xiaoweiFive** [devicekit/DeviceKit#222] opened 2019-11-30 06:55 UTC
<img width="720" alt="image" src="https://user-images.githubusercontent.com/17330916/69896986-810bd780-1380-11ea-9016-0ffae5cd622a.png">

**Comment by wernjie** [comment] 2019-11-30 07:03
This seems to be a duplicate of issue #216 
Do check out commit 0724185 as well

**Closed** 2019-11-30 07:19 UTC
