### ISSUE TITLE
does not support the new devices released at the 2019 September device.

### ISSUE THREAD

**Issue by urm9ril** [devicekit/DeviceKit#202] opened 2019-09-23 02:01 UTC
does not support the new devices released at the 2019 september device.

when I using pods

**Comment by Zandor300** [comment] 2019-09-23 09:57
Duplicate of https://github.com/devicekit/DeviceKit/issues/199

Also, we have merged the changes required for supporting this into master and will release a new version tomorrow to Cocoapods.

**Closed by Zandor300** 2019-09-23 09:57 UTC
