### ISSUE TITLE
not supporting iPhone 11 and higher

### ISSUE THREAD

**Issue by alirzaeram** [devicekit/DeviceKit#208] opened 2019-09-30 10:06 UTC
Please update the library to support iPhone 11, iPhone 11pro and iPhone 11 pro max.

**Comment by denisenepraunig** [comment] 2019-09-30 10:39
Hi @alirzaeram! Since [2.2.0](https://github.com/devicekit/DeviceKit/releases/tag/2.2.0) release last week with [PR 200](https://github.com/devicekit/DeviceKit/pull/200) we support those new device types. My podfile contains ```pod 'DeviceKit', '~> 2.0'```and I've tested it with the integrated Swift package manager in Xcode 11.

Could you share your configuration please so that I could reproduce this error?

**Comment by alirzaeram** [comment] 2019-10-01 02:47
Hi Denise!
Congratulate on your great framework.
I've been testing some ui on iphone 11 and i couldn't found the device.
Can you help me with that?

**Comment by Zandor300** [comment] 2019-10-01 07:25
@alirzaeram Might be because you have to update the framework to add support for iPhone 11 (Pro (Max)).

**Comment by Zandor300** [comment] 2019-10-02 20:11
Closing this for now. If you still have issues, feel free to reopen this issue.

**Closed by Zandor300** 2019-10-02 20:11 UTC
